- name: Set timezone to {{ samba_timezone }}
  community.general.timezone:
    name: "{{ samba_timezone }}"

- name: Get first ip from list
  ansible.builtin.set_fact:
    samba_dc_ipaddresss: "{{ ansible_facts.all_ipv4_addresses[0] }}"

- name: Output hostinfo
  ansible.builtin.debug:
    msg: |
      Hostname: {{ ansible_hostname }}
      IPv4: {{ samba_dc_ipaddresss }}
      Domain: {{ samba_domainname }}

- name: Set hostname to ansible_hostname
  ansible.builtin.hostname:
    name: "{{ ansible_hostname }}"

- name: Edit hostname in hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "127.0.1.1\t{{ ansible_hostname }}"
    state: present
    line: "{{ samba_dc_ipaddresss }}\t{{ ansible_hostname }} {{ ansible_hostname }}.{{ samba_domainname }}"
    backup: true

- name: Copy ntp.conf
  ansible.builtin.copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    backup: true
    force: true
    mode: '644'
